<p>Hola,</p>
<p>gracias por participar en este proyecto. Este apartado contiene información útil para ayudarte en tu labor diaria enseñando programación con el Proyecto Descubre.</p>

<h3>Perfil público</h3>
<p>El nombre de los usuarios del Proyecto Descubre permanece oculto y sólo se muestra su identificador de usuario. Sin embargo, como tutor que eres creemos necesario que tus alumnos puedan reconocerte fácilmente. Por lo tanto, tu nombre real y el centro que hayas indicado al darte de alta en la plataforma, aparecerán en el listado de tutores de la sección <a href="aprende.php">aprende</a>. En cualquier momento puedes cambiar estos datos pinchando en el botón de <a href="editor-usuario.php">'Perfil'</a> que hay en el lado izquierdo.</p>
<p>Cualquier usuario registrado en la plataforma que acceda a tu página de perfil, es decir, ésta en la que te encuentras verá una versión de la misma en la que aparecerán tu nombre real e identificador de usuario, el centro al que perteneces, tu correo electrónico y dos pestañas: programas y grupos. La pestaña 'Programas' mostrará los programas públicos que tengas. La pestaña 'Grupos' mostrará tus grupos al usuario que la visite y le permitirá unirse a ellos o abandonar aquellos en los que ya sea miembro.</p>

<h3>Grupos</h3>
<p>Desde la pestaña 'Grupos' de tu perfil personal podrás crear, modificar y eliminar los grupos que desees. También podrás ver la lista de miembros de los mismos. Para crear un grupo sólo es necesario indicar su nombre y, como recomendación, es interesante indicar el nivel, centro y curso académico del grupo para separar los alumnos por niveles y años académicos. Por ejemplo, "3º ESO IES El Moral (Murcia) - Curso 2015/16" sería un buen nombre de grupo.</p>
<p>En la página que muestra los miembros de un grupo podrás acceder al perfil de cada uno y a la página de análisis de las horas de trabajo del alumno. En esta última podrás ver el tiempo dedicado por el mismo dentro de la web del Proyecto Descubre en el intervalo de tiempo que desees.</p>

<h3>Retos</h3>
<p>Finalmente, además de seguir el curso que proponemos en el apartado <a href="aprende.php">'aprende'</a>, también te recomendamos que crees retos para ellos. Los retos son cojuntos de pruebas, o ejercicios de programación, diseñados para ser evaluados automáticamente por el ordenador. Puedes crear, modificar y consultar los resultados de los retos desde la pestaña 'Retos' de tu perfil personal.</p>
<p>Cada reto tiene un título y una descripción, unas fechas de inicio y de fin, un grupo al que pertenecerá, un nivel de visibilidad y una contraseña.</p>
<p>Las fechas nos permitirán indicar cuándo estará abierto el reto, es decir, cuándo será posible participar e intentar resolver las pruebas que contiene. Si no se indica fecha de inicio ni de fin el reto estará permanentemente abierto, si no se indica fecha de fin pero si de comienzo no se podrá empezar a resolver los problemas hasta dicho momento y si se indican ambas, sólo se podrán resolver en ese intervalo. Es posible indicar fecha y hora por lo que los retos pueden servir para hacer pruebas de evaluación. Además, si se indicara password sólo los que lo conozcan podrán inscribirse en el mismo.</p>
<p>Todos los retos deben pertenecer a un grupo en concreto de modo que sólo los alumnos que estén inscritos en dicho grupo podrán participar en el mismo. Los retos públicos aparecerán en el apartado 'retos' pero sólo para aquellos usuarios que pertenezcan al grupo que tenga asignado el reto.</p>
<p>También es posible hacer que el reto cuente con un ranking público de modo que los alumnos puedan competir entre ellos por obtener el mejor puesto aunque no recomendamos que se haga esto en las pruebas iniciales ni en las de evaluación sino sólo en pruebas optativas.</p>
<p>Una vez guardado el reto, aparecen dos listas en la parte inferior. La lista de la izquierda con las pruebas incluidas en el reto, que estará vacía inicialmente; y la lista de la derecha con las pruebas que se hayan definido hasta el momento. La primera vez esta segunda lista también estará vacía pero pulsando el botón con el símbolo + se va a la página de creación de una prueba.</p>
<p>Usando el ratón puedes incluir las pruebas que quieras en el reto. Basta con arrastrarlas de una lista a otra. También puedes ordenarlas como quieras y volver a sacarlos del reto al conjunto de disponibles, todo pinchando y arrastrando con el ratón.</p>

<h3>Pruebas</h3>
<p>Una prueba se define mediante un título, un enunciado, un nivel de dificultad y su solución. Puedes programar la solución y probarla hasta que estés satisfecho. En la parte inferior también se puede escribir una plantilla de código que sería lo que el alumno vería al iniciar la resolución de la prueba. Una vez guardada la prueba,  en la parte inferior derecha a parecerá el apartado de casos de prueba.</p>
<p>Los casos de prueba se utilizan para verificar si la solución que escriba el alumno es correcta o no. Cada caso de prueba se define con una entrada de texto, que puede ser vacía. Al pulsar en el botón con el símbolo '+' se ejecuta el código de la solución usando como entrada, si es que es necesario, el texto del campo "entrada". Es decir, si en el programa hay alguna función de las que piden datos al usuario: <pre>readInteger, readDouble, readString, readChar</pre> se usará el texto del campo "entrada". Si el programa necesita más de una entrada, estas se separarán con la cadena "\n".</p>
<p>Por ejemplo, si la prueba consiste en escribir un programa que pida dos números enteros y calcule su suma, un caso de prueba válido sería el texto "1\n2" (sin las comillas) y el resultado esperado sería 3.</p>
<p>En general es importante definir varios casos de prueba aunque para algunos tipos de ejercicio no es necesario. Por ejemplo, si el ejercicio tiene siempre la misma salida sólo será necesario un caso de prueba. Esto es así en pruebas básicas, pero necesarias, para que el alumno principante se haga con el manejo del lenguaje. Un ejemplo sería escribir un programa que dibuje un círculo de radio cinco en el centro de la pantalla.</p>
<p>También es posible definir una prueba sin casos de prueba, de este modo cualquier solución será válida. Esto es especialmente útil para ejercicios abiertos, por ejemplo, para plantear un miniconcurso de dibujo usando las funciones gráficas. Todas las soluciones que sean programas sin errores y que funcionen serán aceptadas y el tutor podrá revisarlas al final de la prueba para decidir la nota de cada una.</p>

<h3>Más ayuda</h3>
<p>Si tienes dudas, sugerencias de mejora, encuentras algún error o quieres comentar cualquier cosa puedes escribir a <a href="mailto:descubrelainformatica@um.es">descubrelainformatica@um.es</a>.
</p>